name: Setup Tooling

description: provisions tooling and installs dependancies

runs:
  using: "composite"

  steps:
    - uses: actions/cache@v3
      id: asdf-cache
      with:
        path: ~/.asdf
        key: ${{ runner.os }}-asdf-${{ hashFiles('**/.tool-versions') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: asdf install
      if: steps.asdf-cache.outputs.cache-hit != 'true'
      shell: bash
      run: ./setup.sh

    - name: set asdf path
      shell: bash
      run: |
        echo "$HOME/.asdf/bin" >> $GITHUB_PATH
        echo "$HOME/.asdf/shims" >> $GITHUB_PATH

    - name: Get GO cache directory path
      id: go-cache-dir-path
      run: echo "::set-output name=dir::$(go env GOCACHE)"
      shell: bash

    - uses: actions/cache@v3
      id: go-cache
      with:
        path: ${{ steps.go-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt update -y -qq
        sudo apt install  -y -qq \
          libasound2-dev \
          libc6-dev \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          libxcursor-dev \
          libxi-dev \
          libxinerama-dev \
          libxrandr-dev \
          libxxf86vm-dev \
          pkg-config

    - name: Xvfb
      shell: bash
      run: |
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
