on:
  push:
    branches:
      - master
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled]

name: ci

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
