name: ci

on:
  push:
    branches:
      - master
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup-asdf
      - name: Nodejs
        uses: ./.github/actions/setup-nodejs
      - name: Golang
        uses: ./.github/actions/setup-golang
