name: CodeReview

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Verify:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      actions: write
      pull-requests: read
      checks: read

    steps:
      - uses: actions/checkout@v3
        with:
          # By default, PRs will be checked-out based on the Merge Commit, but we want the actual branch HEAD.
          ref: ${{ github.event.pull_request.head.sha }}
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: master

      - uses: ./.github/actions/setup-tooling
        with:
          SetupCommand: ./setup.sh

      - uses: ./.github/actions/setup-yarn

      - run: just nx workspace-lint

      - run: just lint affected --parallel=3

      - uses: ./.github/actions/setup-os
      - run: just test affected --parallel=3 --ci --code-coverage

      - run: just build affected --parallel=3
