name: pull_request
# https://github.com/marketplace/actions/semantic-pull-request

# This Action ensures that Pullrequests create correct squash commit
# messages on master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  # packages: write
  # issues: write

on:
  pull_request:
    types:
      - assigned
      - opened
      - synchronize
      - reopened
      - labeled
    branches:
      - develop
      - master

jobs:
  validate_title:
    defaults:
      run:
        shell: bash

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup-asdf
      - name: Nodejs
        uses: ./.github/actions/setup-nodejs
      - name: Golang
        uses: ./.github/actions/setup-golang

      - uses: JulienKode/pull-request-name-linter-action@v0.4.0
